spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EstoqueDev?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

topic:
  estoque-uclinic: topic_estoque_kafka
  user-uclinic: topic_user_kafka

server:
  port : 8081
  error:
    include-stacktrace: on_param

